- name: add crowdsec apt-key
  apt_key: 
    url: https://packagecloud.io/crowdsec/crowdsec/gpgkey
    state: present

# https://packagecloud.io/crowdsec/crowdsec/install#manual-deb
- name: add crowdsec apt repository
  apt_repository: 
    repo: deb https://packagecloud.io/crowdsec/crowdsec/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} main
    state: present 
    filename: crowdsec
    update_cache: yes

- name: install crowdsec
  apt: 
    name: crowdsec
    state: present
    update_cache: yes
